### ISSUE TITLE
Обработать стены (плановый ремонт).

### ISSUE THREAD

**Issue by gochankot** [sarfsc/org-projects#1]
Нужно до 8 сентября закупить медный купорос, точечное высушить и обработать стены. После обработки обсыпавшиеся участки нужно закрасить.

**Comment by ghost** [comment]
У меня есть немного медного купороса. Он недорогой, можно купить ещё, однако, из того, что мне известно, это делается иначе: грибок счищается со стен механически, а потом эти участки обрабатываются противогрибковыми средствами.

**Comment by ghost** [comment]
Принесли медный купорос. Много. Надо обрабатывать.

**Comment by mastersin** [comment]
Обработали, но всё вывести не удалось. Летом (когда всё прогреется) нужно повторить, причём в отдельных местах, например, в корридоре перед туалетами.

**Comment by mastersin** [comment]
Обработка стен до сих пор требуется - не хватает ресурсов этим заняться. 

Нужно что-то сделать с пропиткой - купить и проверить.

**Comment by mastersin** [comment]
Стены обваливаются постепенно. Нужно провести по этому поводу беседу с арендодателем. Для этого, желательно, погасить долги и выйти на своевременную оплату.

**Comment by mastersin** [comment]
Больше не актуально.
