### ISSUE TITLE
Проконтролировать подключение заземления.

### ISSUE THREAD

**Issue by gochankot** [sarfsc/org-projects#2]
Нужно, следуя ожидаемым срокам (до сентября) и на связи с арендодателем проследить и проверить подключение заземление в общий щиток и проевить его в зале.

**Comment by ghost** [comment]
@gochankot , @mastersin Задачу закрываем? Считаем ли, что всё норм?

**Comment by gochankot** [comment]
@mastersin, @ValeraSin проконролировали, фото отчет в ВК. Нужно продублировать сюда...
