### ISSUE TITLE
Закупить фанеру (10 листов, 10x1500x1500)

### ISSUE THREAD

**Issue by gochankot** [sarfsc/org-projects#3]

**Comment by ghost** [comment]
Можно ли закрыть задачу? Фанеру купили. Это оно?

**Comment by mastersin** [comment]
Да, фанера закуплена, крепления для материнских плат нарезаны. Правда нам понадобится ещё закупать такую же фанеру для:
- дополнительных креплений;
- робототехнических поделок;
- корпусов под материнки.
