### ISSUE TITLE
Завершить отделку крыльца и установку оборудования на нём.

### ISSUE THREAD

**Issue by gochankot** [sarfsc/org-projects#4]
http://spravkainform.ru/russia/saratov/remont-ustanovka-santehnicheskogo-oborudovaniya/novyy-dom

**Comment by gochankot** [comment]
to @mastersin : Статус задачи?

**Comment by mastersin** [comment]
Всё прошло иначе, дольше и не по плану. В общем, остаются следующие детали:
- [x] покрасить;
- [x] сделать перилла;
- [x] установить лампу (не очень яркую);
- [ ] установить звонок;
- [ ] установить дежурный электронный замок на вход (отключаемый изнутри для выхода, в том числе и с места оператора, в случае звонка);
- [ ] установить камеру и вывести на компютер оператора изображение входа.
